/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "arith.h"
#include <stdlib.h>
#include <time.h>
#include <math.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_SqrtU16(void);
extern void test_SqrtU32(void);
extern void test_RootSumSqU8(void);
extern void test_RootSumSqU16(void);
extern void test_RootSumSqS16(void);
extern void test_SigmaSqU8(void);


/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test-integer_func.c");
  RUN_TEST(test_SqrtU16, 32);
  RUN_TEST(test_SqrtU32, 72);
  RUN_TEST(test_RootSumSqU8, 115);
  RUN_TEST(test_RootSumSqU16, 150);
  RUN_TEST(test_RootSumSqS16, 185);
  RUN_TEST(test_SigmaSqU8, 222);

  return (UnityEnd());
}
