/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "arith.h"
#include "tdd_common.h"
#include <stdlib.h>
#include <time.h>
#include <limits.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_Limits(void);
extern void test_ClipS32toS16(void);
extern void test_ClipU32toU16(void);
extern void test_ClipS32toU16(void);
extern void test_ClipS16toU8(void);
extern void test_ClipU16toU8(void);
extern void test_ClipU32toS32(void);
extern void test_MinS8(void);
extern void test_MaxS8(void);
extern void test_MinS16(void);
extern void test_MaxS16(void);
extern void test_ClipS32(void);
extern void test_ClipU32(void);
extern void test_ClipS16(void);
extern void test_ClipU16(void);
extern void test_ClipU8(void);
extern void test_ClipS8(void);
extern void test_MinU8(void);
extern void test_MaxU8(void);
extern void test_MinU16(void);
extern void test_MaxU16(void);
extern void test_MinU32(void);
extern void test_MaxU32(void);
extern void test_AplusBU8(void);
extern void test_AplusBS16(void);
extern void test_AplusBU16(void);
extern void test_U16plusS16_toU16(void);
extern void test_AplusBU32(void);
extern void test_AplusBS32(void);
extern void test_U32plusS16(void);
extern void test_U32plusS32_toU32(void);
extern void test_SignEqualsS16(void);
extern void test_AminusBU8(void);
extern void test_AminusBU16(void);
extern void test_AminusBS16(void);
extern void test_AminusBU32(void);
extern void test_AminusBU16ToS16(void);
extern void test_AminusBU32toS32(void);
extern void test_AminusBS32toU32(void);
extern void test_AbsS16(void);
extern void test_AbsDiffU8(void);
extern void test_AbsDiffU16(void);
extern void test_AbsDiffS16(void);
extern void test_AbsDiffU32(void);
extern void test_MinusS32(void);
extern void test_Inside_U8(void);
extern void test_Inside_U16(void);
extern void test_Inside_S16(void);
extern void test_InsideEq_U32(void);
extern void test_Mean2_U8(void);
extern void test_Mean3_U8(void);
extern void test_Mean4_U8(void);
extern void test_AmulBdivC_S16(void);
extern void test_AmulBdivC_U16(void);
extern void test_AmulBdivC_U16_rnd(void);
extern void test_AmulBdivC_S16_U8_U8(void);
extern void test_AmulBdivC_U8(void);
extern void test_AmulBdivC_U8_rnd(void);
extern void test_AmulBdivC_S16_S8_S8(void);
extern void test_DeadbandS16(void);
extern void test_Median3_U8(void);
extern void test_Span3_U8(void);
extern void test_Span4_U8(void);
extern void test_SqU8(void);
extern void test_SqU16(void);
extern void test_SqS16(void);
extern void test_MixU8(void);
extern void test_MixU16(void);
extern void test_DecrU8_NowZero(void);
extern void test_DecrU8_Was1_NowZero(void);
extern void test_RankU8_UpTo8(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test-arith_integer_basic.c");
  run_test(test_Limits, "test_Limits", 24);
  run_test(test_ClipS32toS16, "test_ClipS32toS16", 47);
  run_test(test_ClipU32toU16, "test_ClipU32toU16", 72);
  run_test(test_ClipS32toU16, "test_ClipS32toU16", 83);
  run_test(test_ClipS16toU8, "test_ClipS16toU8", 95);
  run_test(test_ClipU16toU8, "test_ClipU16toU8", 109);
  run_test(test_ClipU32toS32, "test_ClipU32toS32", 120);
  run_test(test_MinS8, "test_MinS8", 130);
  run_test(test_MaxS8, "test_MaxS8", 162);
  run_test(test_MinS16, "test_MinS16", 192);
  run_test(test_MaxS16, "test_MaxS16", 222);
  run_test(test_ClipS32, "test_ClipS32", 251);
  run_test(test_ClipU32, "test_ClipU32", 288);
  run_test(test_ClipS16, "test_ClipS16", 325);
  run_test(test_ClipU16, "test_ClipU16", 363);
  run_test(test_ClipU8, "test_ClipU8", 401);
  run_test(test_ClipS8, "test_ClipS8", 439);
  run_test(test_MinU8, "test_MinU8", 479);
  run_test(test_MaxU8, "test_MaxU8", 509);
  run_test(test_MinU16, "test_MinU16", 538);
  run_test(test_MaxU16, "test_MaxU16", 568);
  run_test(test_MinU32, "test_MinU32", 598);
  run_test(test_MaxU32, "test_MaxU32", 628);
  run_test(test_AplusBU8, "test_AplusBU8", 659);
  run_test(test_AplusBS16, "test_AplusBS16", 671);
  run_test(test_AplusBU16, "test_AplusBU16", 701);
  run_test(test_U16plusS16_toU16, "test_U16plusS16_toU16", 730);
  run_test(test_AplusBU32, "test_AplusBU32", 764);
  run_test(test_AplusBS32, "test_AplusBS32", 793);
  run_test(test_U32plusS16, "test_U32plusS16", 824);
  run_test(test_U32plusS32_toU32, "test_U32plusS32_toU32", 858);
  run_test(test_SignEqualsS16, "test_SignEqualsS16", 891);
  run_test(test_AminusBU8, "test_AminusBU8", 933);
  run_test(test_AminusBU16, "test_AminusBU16", 944);
  run_test(test_AminusBS16, "test_AminusBS16", 955);
  run_test(test_AminusBU32, "test_AminusBU32", 969);
  run_test(test_AminusBU16ToS16, "test_AminusBU16ToS16", 981);
  run_test(test_AminusBU32toS32, "test_AminusBU32toS32", 1015);
  run_test(test_AminusBS32toU32, "test_AminusBS32toU32", 1054);
  run_test(test_AbsS16, "test_AbsS16", 1087);
  run_test(test_AbsDiffU8, "test_AbsDiffU8", 1096);
  run_test(test_AbsDiffU16, "test_AbsDiffU16", 1112);
  run_test(test_AbsDiffS16, "test_AbsDiffS16", 1127);
  run_test(test_AbsDiffU32, "test_AbsDiffU32", 1162);
  run_test(test_MinusS32, "test_MinusS32", 1177);
  run_test(test_Inside_U8, "test_Inside_U8", 1191);
  run_test(test_Inside_U16, "test_Inside_U16", 1217);
  run_test(test_Inside_S16, "test_Inside_S16", 1243);
  run_test(test_InsideEq_U32, "test_InsideEq_U32", 1272);
  run_test(test_Mean2_U8, "test_Mean2_U8", 1301);
  run_test(test_Mean3_U8, "test_Mean3_U8", 1325);
  run_test(test_Mean4_U8, "test_Mean4_U8", 1351);
  run_test(test_AmulBdivC_S16, "test_AmulBdivC_S16", 1380);
  run_test(test_AmulBdivC_U16, "test_AmulBdivC_U16", 1440);
  run_test(test_AmulBdivC_U16_rnd, "test_AmulBdivC_U16_rnd", 1490);
  run_test(test_AmulBdivC_S16_U8_U8, "test_AmulBdivC_S16_U8_U8", 1522);
  run_test(test_AmulBdivC_U8, "test_AmulBdivC_U8", 1577);
  run_test(test_AmulBdivC_U8_rnd, "test_AmulBdivC_U8_rnd", 1627);
  run_test(test_AmulBdivC_S16_S8_S8, "test_AmulBdivC_S16_S8_S8", 1657);
  run_test(test_DeadbandS16, "test_DeadbandS16", 1718);
  run_test(test_Median3_U8, "test_Median3_U8", 1791);
  run_test(test_Span3_U8, "test_Span3_U8", 1831);
  run_test(test_Span4_U8, "test_Span4_U8", 1872);
  run_test(test_SqU8, "test_SqU8", 1921);
  run_test(test_SqU16, "test_SqU16", 1933);
  run_test(test_SqS16, "test_SqS16", 1945);
  run_test(test_MixU8, "test_MixU8", 1959);
  run_test(test_MixU16, "test_MixU16", 2001);
  run_test(test_DecrU8_NowZero, "test_DecrU8_NowZero", 2047);
  run_test(test_DecrU8_Was1_NowZero, "test_DecrU8_Was1_NowZero", 2071);
  run_test(test_RankU8_UpTo8, "test_RankU8_UpTo8", 2095);

  return UnityEnd();
}
